"""initial schema

Revision ID: fb5af881ec98
Revises: 
Create Date: 2026-08-23 20:07:56.858767
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb5af881ec98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_rooms_capacity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.CheckConstraint('size > 0', name='ck_student_groups_size_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('student_group_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('sessions_per_week', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('required_room_type', sa.String(length=100), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_activities_duration_minutes_positive'),
    sa.CheckConstraint('sessions_per_week > 0', name='ck_activities_sessions_per_week_positive'),
    sa.ForeignKeyConstraint(['student_group_id'], ['student_groups.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_student_group_id'), 'activities', ['student_group_id'], unique=False)
    op.create_index(op.f('ix_activities_teacher_id'), 'activities', ['teacher_id'], unique=False)
    op.create_table('room_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='ck_room_availability_time_range'),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_room_availability_weekday'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_availability_room_id'), 'room_availability', ['room_id'], unique=False)
    op.create_table('schedule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'SUPERSEDED', name='scheduleversionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solver_status', sa.String(length=20), nullable=False),
    sa.Column('solve_duration_seconds', sa.Float(), nullable=False),
    sa.Column('solver_metadata', sa.JSON(), nullable=False),
    sa.CheckConstraint('version_number > 0', name='ck_schedule_versions_number_positive'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'version_number', name='uq_schedule_version_number')
    )
    op.create_index(op.f('ix_schedule_versions_schedule_id'), 'schedule_versions', ['schedule_id'], unique=False)
    op.create_index('uq_schedule_one_published_version', 'schedule_versions', ['schedule_id'], unique=True, postgresql_where=sa.text("status = 'PUBLISHED'"), sqlite_where=sa.text("status = 'PUBLISHED'"))
    op.create_table('teacher_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='ck_availability_time_range'),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_availability_weekday'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_availability_teacher_id'), 'teacher_availability', ['teacher_id'], unique=False)
    op.create_table('scheduled_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_version_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('session_index', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_group_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('time_slot_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_scheduled_lessons_duration_positive'),
    sa.CheckConstraint('session_index >= 0', name='ck_scheduled_lessons_session_nonnegative'),
    sa.CheckConstraint('start_time < end_time', name='ck_scheduled_lessons_time_range'),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_scheduled_lessons_weekday'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], ),
    sa.ForeignKeyConstraint(['student_group_id'], ['student_groups.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_version_id', 'activity_id', 'session_index', name='uq_scheduled_lesson_session')
    )
    op.create_index(op.f('ix_scheduled_lessons_activity_id'), 'scheduled_lessons', ['activity_id'], unique=False)
    op.create_index(op.f('ix_scheduled_lessons_room_id'), 'scheduled_lessons', ['room_id'], unique=False)
    op.create_index(op.f('ix_scheduled_lessons_schedule_version_id'), 'scheduled_lessons', ['schedule_version_id'], unique=False)
    op.create_index(op.f('ix_scheduled_lessons_student_group_id'), 'scheduled_lessons', ['student_group_id'], unique=False)
    op.create_index(op.f('ix_scheduled_lessons_teacher_id'), 'scheduled_lessons', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_lessons_teacher_id'), table_name='scheduled_lessons')
    op.drop_index(op.f('ix_scheduled_lessons_student_group_id'), table_name='scheduled_lessons')
    op.drop_index(op.f('ix_scheduled_lessons_schedule_version_id'), table_name='scheduled_lessons')
    op.drop_index(op.f('ix_scheduled_lessons_room_id'), table_name='scheduled_lessons')
    op.drop_index(op.f('ix_scheduled_lessons_activity_id'), table_name='scheduled_lessons')
    op.drop_table('scheduled_lessons')
    op.drop_index(op.f('ix_teacher_availability_teacher_id'), table_name='teacher_availability')
    op.drop_table('teacher_availability')
    op.drop_index('uq_schedule_one_published_version', table_name='schedule_versions', postgresql_where=sa.text("status = 'PUBLISHED'"), sqlite_where=sa.text("status = 'PUBLISHED'"))
    op.drop_index(op.f('ix_schedule_versions_schedule_id'), table_name='schedule_versions')
    op.drop_table('schedule_versions')
    op.drop_index(op.f('ix_room_availability_room_id'), table_name='room_availability')
    op.drop_table('room_availability')
    op.drop_index(op.f('ix_activities_teacher_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_student_group_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('teachers')
    op.drop_table('student_groups')
    op.drop_table('schedules')
    op.drop_table('rooms')
    # ### end Alembic commands ###
